### ISSUE TITLE
Battleground Emissaries Spawning on top of each other

### ISSUE THREAD

**Issue by havox112** [ProjectNagrand/GaradarBugReports#8]
![wowscrnshot_030717_160209](https://cloud.githubusercontent.com/assets/26206818/23680049/7d61a748-034f-11e7-9a06-47baeae03bbf.jpg)
![wowscrnshot_030717_160352](https://cloud.githubusercontent.com/assets/26206818/23680111/b1998b20-034f-11e7-8470-c167a77680ac.jpg)

**Comment by JorinGaradar** [comment]
Resolved issue, thanks for reporting!
